### ISSUE TITLE
get threaddump from all pods with label

### ISSUE THREAD

**Issue by cloud-66** [josepdcs/kubectl-prof#46]
I have 10 replicas of service. If there is a problem with service i don't know which replica is affected by problem, and i should get threaddump from all pod replicas 
how it could work
```
kubectl logs -f -l app=myappname
```
in a similar way with label

```
 kubectl prof -l app=myappname --interval 10s -t 120s -l java -o threaddump --image=registry/systemtest/kubectl-prof:1.2.5-jvm
``
result:
podname1-threaddump.txt
podname2-threaddump.txt
..

**Comment by josepdcs** [comment]
It' a good thing to support this functionality.

**Comment by josepdcs** [comment]
@cloud-66, released into  https://github.com/josepdcs/kubectl-prof/releases/tag/1.3.0
