### ISSUE TITLE
Support for specify process name

### ISSUE THREAD

**Issue by SSmallMonster** [josepdcs/kubectl-prof#8]
First of all, @josepdcs thank you for your efforts, this project is the best supported project for performance sampling so far.

When a application container that contains multiple processes require specifying the target process name when capturing. Just like the --pgrep parameter inside the [upstream](https://github.com/yahoo/kubectl-flame)

**Comment by SSmallMonster** [comment]
If it's okay, I can contribute this feature :-)

**Comment by josepdcs** [comment]
WIP @SSmallMonster ;-)

**Comment by josepdcs** [comment]
Added to my TODO :-)

**Comment by SSmallMonster** [comment]
> Added to my TODO :-)

That's great!!

**Comment by josepdcs** [comment]
Hi, @SSmallMonster it's already solved in [1.2.0](https://github.com/josepdcs/kubectl-prof/releases/tag/1.2.0) :-))

**Comment by SSmallMonster** [comment]
> Hi, @SSmallMonster it's already solved in [1.2.0](https://github.com/josepdcs/kubectl-prof/releases/tag/1.2.0) :-))

Awaresome!
